### ISSUE TITLE
Terrible performance when using dynamic messages

### ISSUE THREAD

**Issue by oridag** [google/cel-java#119]
Since`LazyGeneratedMessageDefaultInstance.getDefaultInstance`'s result is not cached when class lookup fails, when working with dynamic messages it is called over and over, generating a `ClassNotFoundExcpetion` (along with its stack trace) resulting in a very slow evaluation

**Comment by l46kok** [comment]
Would you mind posting a repro for this? Having a `DynamicMessage` indicates that you have a descriptor for it, and if the environment has the descriptor added, you shouldn't be getting an error when attempting to construct a default instance.

**Comment by oridag** [comment]
`Class.forName` in `LazyGeneratedMessageDefaultInstance.loadDefaultInstance` throws a `ClassNotFoundException`, which is caught, but since `defaultInstance` remains `null`, it will be called over and over.

Here is a small Scala repro:
```scala
object Repro extends App {

  val messageDescProto = DescriptorProto.newBuilder()
    .setName("Message")
    .addField(FieldDescriptorProto.newBuilder().setNumber(1).setName("f1").setType(FieldDescriptorProto.Type.TYPE_FLOAT))
    .build()

  val fdp = FileDescriptorProto.newBuilder()
    .addMessageType(messageDescProto)
    .build()

  val fd = FileDescriptor.buildFrom(fdp, Array.empty)

  val celRuntime = CelRuntimeFactory.standardCelRuntimeBuilder()
    .addFileTypes(fd)
    .build()

  val cel = CelFactory
    .standardCelBuilder
    .addFileTypes(fd)
    .build()

  val start = System.currentTimeMillis()
  val compiledExp = cel.compile("Message { f1: 0.5 }")
  val program = celRuntime.createProgram(compiledExp.getAst)
  (0 until 1000 * 1000).foreach(_ => program.eval())
  val end = System.currentTimeMillis()
  println((end - start) / 1000.0 + " seconds")


}
```
On my local machine this runs in about 12 seconds.

If I change `getDefaultInstance` from this:
```java
    public Message getDefaultInstance() {
      if (defaultInstance == null) {
        synchronized (this) {
          if (defaultInstance == null) {
            loadDefaultInstance();
          }
        }
      }
      return defaultInstance;
    }
```
to this:
```java
    public Message getDefaultInstance() {
      if (!loaded) {
        synchronized (this) {
          if (!loaded) {
            loadDefaultInstance();
            loaded = true;
          }
        }
      }
      return defaultInstance;
    }

```
it runs in about 900 milliseconds.

I can offer a PR if you prefer.

**Comment by l46kok** [comment]
I see, manually constructed descriptors won't return a default instance and that will definitely fail repeatedly. What you proposed sounds good to me. At the moment, we haven't fully setup our copybara syncing process to be able to directly accept external contributions, so you may not get accredited in Github (I will likely have to copy the PR verbatim and sync it from our side). If you're OK with that, we'd be happy to accept your PR.

**Comment by oridag** [comment]
Well that's pretty much all the change. The only line missing is the member declaration:
```java
private volatile boolean loaded = false;
```

**Comment by l46kok** [comment]
Fix has been merged. Thanks for filing the issue and providing the fix

**Comment by oridag** [comment]
Thank you. Is there a planned release anytime soon?

**Comment by l46kok** [comment]
I just kicked off a maven artifact release. You can expect it to be available within hours.
