### ISSUE TITLE
How to create custom function and custom object

### ISSUE THREAD

**Issue by faint-star** [google/cel-java#159]
How to create custom function and object. Are there more examples?

**Comment by l46kok** [comment]
Hi,

We're actively working on publishing codelab exercises. For time being, you could reference the examples here (exercise 4 is about custom functions): https://github.com/google/cel-java/pull/161/files#diff-e0d2190de82384d3073583e9f4340b4474c86c1ea9cd6d4f4e22232eca1d8a51

We'll announce the codelabs link when it's publicly available.

**Comment by l46kok** [comment]
Please refer to the codelab README: https://github.com/google/cel-java/blob/main/codelab/README.md
