### ISSUE TITLE
[BUG] Build failure on Mac OSX

### ISSUE THREAD

**Issue by mikedanese** [google/cel-java#193]
**Describe the bug**
`//publish:cel.publish` doesn't build on Mac OS. Full error message is below.

I believe the problem is that [parser/src/main/java/dev/cel/parser/CelParser.java](https://github.com/google/cel-java/blob/cf3d719adf01afd7e0837d2a4e679ec8048f4172/parser/src/main/java/dev/cel/parser/CelParser.java) conflicts with CELParser.java generated by the antlr build rule here:

https://github.com/google/cel-java/blob/cf3d719adf01afd7e0837d2a4e679ec8048f4172/parser/src/main/java/dev/cel/parser/BUILD.bazel#L106-L112

And the default filesystem of MacOS does not have case sensitive file paths. This (https://support.apple.com/lt-lt/guide/disk-utility/dsku19ed921c/mac) looks like the most official documentation of this behavior, and I believe you need to do a full disk reformat to fix so not easy to workaround.

**To Reproduce**

On OSX:

```console
$ bazel build //publish:cel.publish
INFO: Analyzed target //publish:cel.publish (0 packages loaded, 0 targets configured).
INFO: From Action publish/cel-docs.jar:
javadoc -cp ....
javadoc: warning - You have specified to generate frames, by using the --frames option.
The default is currently to not generate frames and the support for
frames will be removed in a future release.
To suppress this warning, remove the --frames option and avoid the use of frames.
/var/folders/f9/sc20dw5134n9vxn6np883f5c0000gp/T/unpacked-sources790206605151880537/dev/cel/parser/CELParser.java:24: error: interface CelParser is public, should be declared in a file named CelParser.java
public interface CelParser {
       ^
1 error
1 warning

ERROR: /Users/mike.danese/code/cel-java/publish/BUILD.bazel:52:12: output 'publish/cel-docs.jar' was not created
ERROR: /Users/mike.danese/code/cel-java/publish/BUILD.bazel:52:12: output 'publish/cel-docs-element-list-dir/element-list' was not created
ERROR: /Users/mike.danese/code/cel-java/publish/BUILD.bazel:52:12: Action publish/cel-docs.jar failed: not all outputs were created or valid
Target //publish:cel.publish failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.182s, Critical Path: 2.03s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
ERROR: Build did NOT complete successfully
```

**Comment by l46kok** [comment]
AFAIK, this is a Bazel limitation: https://github.com/bazelbuild/bazel/issues/7627. Java builds are especially susceptible because it caches all of the java classes in the same location.

If the ANTLR generated code is the only problem, I'd be OK with changing its class name to sidestep this (e.g: `CELInternalParser.java`). I don't have a good way of confirming this. Please feel free to open a PR, I'd be happy to take a look.

**Comment by mikedanese** [comment]
Here you go: https://github.com/google/cel-java/pull/194
