### ISSUE TITLE
Support trivial comprehensions in constant folding

### ISSUE THREAD

**Issue by oridag** [google/cel-java#200]
The expression `cel.bind(a, 1, a + arg)` is macro expanded into a trivial comprehension that doesn't loop and assigns `1` to the accum_var, so theoretically it can be folded into `1 + arg`. Is that possible to support that case in the constant folding optimizer?

**Comment by oridag** [comment]
Alternatively, or additionally, perhaps the parser can be smart enough to handle the case where the bind argument is a constant and expand the macro to replace all references to the parameter with the constant instead of creating a comprehension

**Comment by l46kok** [comment]
For `cel.bind` specifically -- we have plans to make it lazily evaluable across all languages ([cpp has done this recently](https://github.com/google/cel-cpp/commit/d97dbb71b62de914d2e48765d4398115aa817b9c)) to allow us to support certain advanced constructs and optimizers such as CSE. In this scenario, performing constant propagation may yield an expression with different semantics in expressions where the bound variable lies within a non-strict function (ternary for example).
