### ISSUE TITLE
Calling `CelRuntimeBuilder.setStandardEnvironmentEnabled(false)` does not disable standard functions

### ISSUE THREAD

**Issue by modhanami** [google/cel-java#255]
**Note**

I see `StandardFunctions.add()` being called twice in `CelRuntimeLegacyImpl.build()`, once in `DefaultDispatcher.create()` unconditionally, and another when `standardEnvironmentEnabled` is true.

Are these intended? Or how can I disable the standard functions completely to achieve something like cel-go's `NewCustomEnv`?

https://github.com/google/cel-java/blob/4f8f4551a14fdea074c7c14077c1c3dd89b3d145/runtime/src/main/java/dev/cel/runtime/CelRuntimeLegacyImpl.java#L230-L233

https://github.com/google/cel-java/blob/4f8f4551a14fdea074c7c14077c1c3dd89b3d145/runtime/src/main/java/dev/cel/runtime/DefaultDispatcher.java#L76-L80

**Comment by l46kok** [comment]
This is most definitely unintended. https://github.com/google/cel-java/pull/256 should fix this when it lands.

Thanks for reporting.
