### ISSUE TITLE
Strict type checking

### ISSUE THREAD

**Issue by oridag** [google/cel-java#358]
Sometimes a strict type checking is required for the result type. Currently, when the result type is dynamic, AST checking passes no matter what the expected result type is.
For example, the expression `["a", 0.1][0]` will pass both checking and evaluation, no matter what `setResultType` is set to. In cases where a dynamic return type is illegal it is required to reject the expression as invalid.

Having a `strictResultType` flag on the compiler will be great. Alternatively (and maybe useful in general), if the result type can be checked explicitly, (e.g. `checkedAst.getResultType()`) then one can make sure it is not `Dyn` when checking the expression.

**Comment by l46kok** [comment]
You can actually leverage `getResultType` today to check the result type explicitly: https://github.com/google/cel-java/blob/main/common/src/main/java/dev/cel/common/CelAbstractSyntaxTree.java#L104. This should return `Dyn` for the example you've shown.

There is also an option to disallow heterogenous literals in lists and maps by leveraging HomogeneousLiteralValidator. This is usually the commonly needed feature. See: [relevant codelab exercise](https://github.com/google/cel-java/tree/main/codelab#static-ast-validators-and-optimizers).

To answer the question, the behavior you're seeing with the type-checker is consistent with [the specification](https://github.com/google/cel-java/tree/main/codelab#static-ast-validators-and-optimizers) and with cel-go implementation. List with mixed types is type-checked as `list(dyn)`, and `dyn` is a union of all types so the type-checker will defer the type agreement check of the list elements to the runtime. If we wanted to perform a stronger type-check on the elements, we'd need to do a function dispatch for the indexer, in which case an `AstValidator` is more suitable for such tasks.
