### ISSUE TITLE
CEL-Java?

### ISSUE THREAD

**Issue by snazy** [google/cel-java#37]
I'm one of the maintainers of [CEL-Java](https://github.com/projectnessie/cel-java/), which exists for quite a while now and is used in production. It is inspired by CEL-Go and has all the features CEL-Go has plus support for Jackson.

I wonder whether it would be beneficial to join forces and only have one implementation instead of two "competing" CEL-Java implementations. We're open to discuss options regarding a joint effort.

**Comment by l46kok** [comment]
Hi @snazy, thanks for reaching out. For context, we're in the midst of on open-sourcing the rest of CEL-Java implementation (parser + type-checker) that exists internally at Google. This is expected to happen by Q3 of this year and we aren't able to accept any contributions until then. We'd be happy for discussing options for a joint effort. Could you share an email address that we can start a thread on?

**Comment by l46kok** [comment]
Please reach out if you haven't received an email from us. I apologize about the delay
