### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by buildbreaker** [google/cel-java#68]
👋 I'm looking to give this repository a shot but I'm finding that the examples in the README are incomplete and the Examples directory in the table of contents goes to a 404.

Do you happen to have a snippet of how to construct a CelProgram and evaluate a simple expression with an Activation?

**Comment by l46kok** [comment]
Hi, [here's an example I've crafted with a handrolled Checked expression](https://github.com/l46kok/cel-java-playground).

Once the CEL-Java compiler is fully open sourced, we hope to provide some canonical materials demonstrating its usage. Hopefully this helps.
